Update environment.yml / eliminate windows only packages
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested vc 14.1**
  - nothing provides requested vs2015_runtime 14.16.27012**
  - nothing provides __win needed by wincertstore-0.2-pyhd8ed1ab_1009

Could not solve for environment specs
The following packages are incompatible
├─ vc 14.1**  does not exist (perhaps a typo or a missing channel);
├─ vs2015_runtime 14.16.27012**  does not exist (perhaps a typo or a missing channel);
└─ wincertstore 0.2**  is not installable because it requires
   └─ __win, which is missing on the system.